### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [AntonioFry/mod_0_skills#1]
# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub
* [x]  Directories are named correctly.
* [x]  Files are named correctly.
* [x]  Files and directories are structured correctly.
* [x]  Initial commit was made.
* [x]  Initial commit was pushed to GitHub.

#### Part II: Top Down Design
* [x]  Larger processes were broken into smaller layers.
* [x]  Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
* [x]  Changes were pushed to Github.

#### Part III: Classes in a System
* [x]  Directories and files were named and structured correctly.
* [x]  The attributes chosen for **Class #1** represent states or characteristics.
* [x]  The attributes chosen for **Class #2** represent states or characteristics.
* [ ]  The attributes chosen for **Class #3** represent states or characteristics.
> I'm a little confused by this class. Think of classes as nouns (Customer, Order, Menu_Item, Furniture, etc.) that have clearly defined attributes and behaviors/actions. `Retrieval Method` seems more like it would belong as an attribute on the `Order` class. 
* [x]  The methods chosen for **Class #1** represent behaviors or actions.
* [x]  The methods chosen for **Class #2** represent behaviors or actions.
* [ ]  The methods chosen for **Class #3** represent behaviors or actions.
> (see comment above about Class 3) 
* [x]  Data type (string, integer, boolean, array, hash/object, datetime) were identified for each attribute in all three classes.
* [ ]  Individual changes were added and committed separately with a properly formatted commit message.
With commit messages, make sure that the message represents the changes you made in that specific segment of work. Instead of using the same commit messages (which can get quite confusing later if you have to go back to rework something), try to make your commit messages reflect the work you did. For example, `Add attributes and methods to Entree class` would be a message that would I would understand when revisiting my work later. 
<img width="313" alt="screen shot 2019-02-27 at 1 43 31 pm" src="https://user-images.githubusercontent.com/3311609/53525871-9d987d80-3a97-11e9-909d-b63b5814fd0f.png">

* [x]  Changes were pushed to Github.

**Mod 0 Technical Assessment Results**

* [ ]   Technical Ready
* [x]   Pending
> Next steps: Redo Class #3. Try to chose a class (noun) that has clearly defined attributes and behaviors. When you commit, use a specific message. 
* [ ]   Not Ready

**Comment by rwarbelow** [comment]
@AntonioFry Changes look good!
- [x] Technical Ready
